export const wordList = [
  {
    id: 0,
    list: [
      { id: 0, day: 1, word: "celebration", meaning: "축하, 기념행사" },
      { id: 1, day: 1, word: "worm", meaning: "벌레" },
      { id: 2, day: 1, word: "region", meaning: "지역" },
      { id: 3, day: 1, word: "unique", meaning: "독특한" },
      { id: 4, day: 1, word: "associate", meaning: "관련시키다" },
      { id: 5, day: 1, word: "carving", meaning: "조각하기, 조각" },
      { id: 6, day: 1, word: "take place", meaning: "발생하다" },
      { id: 7, day: 1, word: "come upon -", meaning: "-와 우연히 미주치다" },
      {
        id: 8,
        day: 1,
        word: "go hand in hand",
        meaning: "공존하다, 서로 연관되다",
      },
      { id: 9, day: 1, word: "exhibit", meaning: "전시하다" },
    ],
  },
  {
    id: 1,
    list: [
      { id: 0, day: 2, word: "offer", meaning: "제공하다" },
      { id: 1, day: 2, word: "lobster", meaning: "바닷가재" },
      { id: 2, day: 2, word: "ingredient", meaning: "재료, 성분" },
      { id: 3, day: 2, word: "local", meaning: "지역의" },
      { id: 4, day: 2, word: "clam", meaning: "조개" },
      { id: 5, day: 2, word: "crate", meaning: "(나무)상자" },
      { id: 6, day: 2, word: "participant", meaning: "참가자" },
      { id: 7, day: 2, word: "float", meaning: "뜨다, 떠다니다" },
      { id: 8, day: 2, word: "volunteer", meaning: "자원봉사자" },
      { id: 9, day: 2, word: "organizer", meaning: "주최자, 조직자" },
    ],
  },
  {
    id: 2,
    list: [
      { id: 0, day: 3, word: "fisherman", meaning: "어부" },
      { id: 1, day: 3, word: "imaginable", meaning: "상상할 수 있는" },
      { id: 2, day: 3, word: "season", meaning: "양념하다" },
      { id: 3, day: 3, word: "award", meaning: "수여하다" },
      { id: 4, day: 3, word: "traditional", meaning: "전통적인" },
      { id: 5, day: 3, word: "take part in", meaning: "~에 참가하다" },
      { id: 6, day: 3, word: "regard - as", meaning: "-을 ...로 여기다" },
      { id: 7, day: 3, word: "emphasize", meaning: "강조하다" },
      { id: 8, day: 3, word: "predetermined", meaning: "미리 결정된" },
      { id: 9, day: 3, word: "philosopher", meaning: "철학자" },
    ],
  },
  {
    id: 3,
    list: [
      { id: 0, day: 4, word: "promote", meaning: "촉진하다" },
      { id: 1, day: 4, word: "incredibly", meaning: "믿을 수 없을 만큼" },
      { id: 2, day: 4, word: "cognitive", meaning: "인식의" },
      { id: 3, day: 4, word: "bias", meaning: "편견" },
      { id: 4, day: 4, word: "abstract", meaning: "추상적인" },
      { id: 5, day: 4, word: "concept", meaning: "개념" },
      { id: 6, day: 4, word: "forbid", meaning: "금지하다" },
      { id: 7, day: 4, word: "religion", meaning: "종교" },
      { id: 8, day: 4, word: "declare", meaning: "선언하다" },
      { id: 9, day: 4, word: "transaction", meaning: "거래" },
    ],
  },
  {
    id: 4,
    list: [
      { id: 0, day: 5, word: "conduct", meaning: "실행하다" },
      { id: 1, day: 5, word: "dweller", meaning: "거주자" },
      { id: 2, day: 5, word: "literally", meaning: "문자 그대로" },
      { id: 3, day: 5, word: "analogy", meaning: "비유" },
      { id: 4, day: 5, word: "drown", meaning: "물에 빠지다" },
      { id: 5, day: 5, word: "alternatively", meaning: "대안으로" },
      { id: 6, day: 5, word: "extreme", meaning: "극단, 극도의" },
      { id: 7, day: 5, word: "in action", meaning: "작용하는" },
      { id: 8, day: 5, word: "bribe", meaning: "뇌물(을 주다)" },
      { id: 9, day: 5, word: "virtue", meaning: "미덕" },
    ],
  },
  {
    id: 5,
    list: [
      { id: 0, day: 6, word: "perspective", meaning: "관점, 시각" },
      { id: 1, day: 6, word: "phase", meaning: "단계, 국면" },
      { id: 2, day: 6, word: "physical", meaning: "물리적인" },
      { id: 3, day: 6, word: "political", meaning: "정치적인" },
      { id: 4, day: 6, word: "suspend", meaning: "일시적으로 중지하다" },
      { id: 5, day: 6, word: "predict", meaning: "예측하다, 예견하다" },
      { id: 6, day: 6, word: "prefer", meaning: "~을 선호하다" },
      { id: 7, day: 6, word: "benefit", meaning: "혜택" },
      { id: 8, day: 6, word: "previlege", meaning: "특혜" },
      { id: 9, day: 6, word: "prevent", meaning: "막다, 예방하다" },
    ],
  },
  {
    id: 6,
    list: [
      { id: 0, day: 8, word: "process", meaning: "과정" },
      { id: 1, day: 8, word: "comfortabie", meaning: "편한, 기분좋은" },
      { id: 2, day: 8, word: "competition", meaning: "경쟁, 대회" },
      { id: 3, day: 8, word: "complete", meaning: "채우다, 완료하다" },
      { id: 4, day: 8, word: "condition", meaning: "조건" },
      { id: 5, day: 8, word: "anthropologist", meaning: "인류학자" },
      { id: 6, day: 8, word: "confirm", meaning: "확정하다, 확인하다" },
      { id: 7, day: 8, word: "conflict", meaning: "갈등" },
      { id: 8, day: 8, word: "consequence", meaning: "결과" },
      { id: 9, day: 8, word: "consider", meaning: "고려하다" },
    ],
  },
  {
    id: 7,
    list: [
      { id: 0, day: 8, word: "contact", meaning: "접촉" },
      { id: 1, day: 8, word: "contain", meaning: "들어있다, 포함하다" },
      { id: 2, day: 8, word: "contemporary", meaning: "현대의, 동시대의" },
      { id: 3, day: 8, word: "context", meaning: "백락, 상황" },
      { id: 4, day: 8, word: "contribution", meaning: "기부, 기여" },
      { id: 5, day: 8, word: "cooperation", meaning: "협조" },
      { id: 6, day: 8, word: "a variety of", meaning: "다양한, 여러가지의" },
      { id: 7, day: 8, word: "according to", meaning: "~에 따르면, 의하면" },
      { id: 8, day: 8, word: "account for", meaning: "~을 차지하다" },
      { id: 9, day: 8, word: "apply for", meaning: "~에 지원하다/신청하다" },
    ],
  },
  {
    id: 8,
    list: [
      { id: 0, day: 9, word: "associate with", meaning: "~를 관련시키다" },
      { id: 1, day: 9, word: "at least", meaning: "적어도" },
      { id: 2, day: 9, word: "attempt to", meaning: "~하려고 시도하다" },
      { id: 3, day: 9, word: "based on", meaning: "~에 기반을 둔" },
      { id: 4, day: 9, word: "be responsible for", meaning: "~에 책임이 있는" },
      { id: 5, day: 9, word: "result in", meaning: "결국 하게 되다" },
      { id: 6, day: 9, word: "set up", meaning: "자립하다" },
      { id: 7, day: 9, word: "show off", meaning: "~을 자랑하다" },
      { id: 8, day: 9, word: "side effect", meaning: "부작용" },
      { id: 9, day: 9, word: "altitude", meaning: "고도" },
    ],
  },
  {
    id: 9,
    list: [
      { id: 0, day: 10, word: "take care of", meaning: "돌보다" },
      { id: 1, day: 10, word: "take place", meaning: "열리다, 개최되다" },
      { id: 2, day: 10, word: "tend to", meaning: "~하는 경향이 있다" },
      { id: 3, day: 10, word: "temperature", meaning: "온도, 기온" },
      { id: 4, day: 10, word: "temporarily", meaning: "일시적으로, 임시로" },
      { id: 5, day: 10, word: "in terms of", meaning: "~의 면에서" },
      { id: 6, day: 10, word: "threat", meaning: "협박, 위협" },
      { id: 7, day: 10, word: "throughout", meaning: "~내내, ~동안" },
      { id: 8, day: 10, word: "tragedy", meaning: "비극" },
      { id: 9, day: 10, word: "tropical", meaning: "열대의, 열대 지방의" },
    ],
  },
  {
    id: 10,
    list: [
      { id: 0, day: 11, word: "architecture", meaning: "건축" },
      { id: 1, day: 11, word: "relevant", meaning: "관련된" },
      { id: 2, day: 11, word: "insert", meaning: "주입하다. 넣다" },
      { id: 3, day: 11, word: "elevation", meaning: "높이, 고도" },
      { id: 4, day: 11, word: "means", meaning: "수단" },
      { id: 5, day: 11, word: "ritual", meaning: "의식" },
      { id: 6, day: 11, word: "convincing", meaning: "설득력 있는" },
      { id: 7, day: 11, word: "overestimate", meaning: "과대평가하다" },
      { id: 8, day: 11, word: "sign up for", meaning: "~에 등록하다" },
      { id: 9, day: 11, word: "hypothesis", meaning: "가설" },
    ],
  },
  {
    id: 11,
    list: [
      { id: 0, day: 12, word: "temptation", meaning: "유혹" },
      { id: 1, day: 12, word: "nutritious", meaning: "영양가 많은" },
      { id: 2, day: 12, word: "concentrate", meaning: "집중하다" },
      { id: 3, day: 12, word: "run out of", meaning: "-을 다써버리다" },
      { id: 4, day: 12, word: "material", meaning: "자료, 재료" },
      {
        id: 5,
        day: 12,
        word: "be committed to-",
        meaning: "-에 전념/헌신하다",
      },
      { id: 6, day: 12, word: "regardless of", meaning: "-에 관계없이" },
      { id: 7, day: 12, word: "in favor of", meaning: "-에 찬성하여" },
      { id: 8, day: 12, word: "in contrast", meaning: "그에 반해서" },
      { id: 9, day: 12, word: "pull back", meaning: "물러나다. 후퇴하다" },
    ],
  },
  {
    id: 12,
    list: [
      { id: 0, day: 13, word: "be through", meaning: "끝내다. 마치다" },
      { id: 1, day: 13, word: "self-confidence", meaning: "자신감" },
      { id: 2, day: 13, word: "in advance", meaning: "미리, 앞서서" },
      {
        id: 3,
        day: 13,
        word: "stand against",
        meaning: "-에 맞서다. 대항하다",
      },
      { id: 4, day: 13, word: "on behalf of", meaning: "~을 위해" },
      { id: 5, day: 13, word: "cope with", meaning: "-에 대처하다" },
      { id: 6, day: 13, word: "up(on) ~ing", meaning: "~하자마자" },
      { id: 7, day: 13, word: "interpret", meaning: "해석하다" },
      { id: 8, day: 13, word: "absent-minded", meaning: "딴 데 정신이 팔린" },
      {
        id: 9,
        day: 13,
        word: "keep track of",
        meaning: "-을 기록하다/추적하다",
      },
    ],
  },
  {
    day: 15,
    id: 13,
    list: [
      { id: 0, day: 14, word: "rather than", meaning: "-라기보다는" },
      { id: 1, day: 14, word: "submit", meaning: "제출하다" },
      { id: 2, day: 14, word: "suggest", meaning: "제안하다, 제시하다" },
      { id: 3, day: 14, word: "puddle", meaning: "웅덩이" },
      { id: 4, day: 14, word: "support", meaning: "부양, 지지하다" },
      { id: 5, day: 14, word: "survival", meaning: "생존" },
      { id: 6, day: 14, word: "task", meaning: "과업" },
      { id: 7, day: 14, word: "technological", meaning: "기술적인" },
      { id: 8, day: 14, word: "tendency", meaning: "경향, 추세" },
      { id: 9, day: 14, word: "term", meaning: "용어" },
    ],
  },
  {
    id: 14,
    list: [
      { id: 0, day: 15, word: "unfortunately", meaning: "불행하게도" },
      { id: 1, day: 15, word: "revolution", meaning: "혁명" },
      { id: 2, day: 15, word: "differ from", meaning: "~와 다르다" },
      { id: 3, day: 15, word: "pros and cons", meaning: "찬반토론" },
      { id: 4, day: 15, word: "deal with", meaning: "~을 다루다" },
      { id: 5, day: 15, word: "dispose of", meaning: "-을 처리하다, 없애다" },
      { id: 6, day: 15, word: "keep in mind", meaning: "명심하다" },
      { id: 7, day: 15, word: "look forward to", meaning: "~을 기대하다" },
      { id: 8, day: 15, word: "gaze", meaning: "응시하다" },
      { id: 9, day: 15, word: "due to", meaning: "때문에, 로 인해" },
    ],
  },
  {
    id: 15,
    list: [
      { id: 0, day: 16, word: "release", meaning: "방출하다, 풀어놓다" },
      { id: 1, day: 16, word: "relieved", meaning: "안도하는" },
      { id: 2, day: 16, word: "psychological", meaning: "심리적인, 정신적인" },
      { id: 3, day: 16, word: "purchase", meaning: "구매하다, 구입하다" },
      { id: 4, day: 16, word: "quality", meaning: "(품)질" },
      { id: 5, day: 16, word: "recognize", meaning: "인식하다, 인지하다" },
      { id: 6, day: 16, word: "recommend", meaning: "추천하다" },
      { id: 7, day: 16, word: "reflect", meaning: "반영하다" },
      { id: 8, day: 16, word: "surrender", meaning: "굴복하다, 항복하다" },
      { id: 9, day: 16, word: "evidence", meaning: "증거" },
    ],
  },
  {
    id: 16,
    list: [
      { id: 0, day: 17, word: "regularly", meaning: "규칙적으로" },
      { id: 1, day: 17, word: "reinforce", meaning: "강화하다" },
      {
        id: 2,
        day: 17,
        word: "compensate for",
        meaning: "을 보상하다, 보충하다",
      },
      { id: 3, day: 17, word: "plunge to", meaning: "~에 쑤셔박다, 일어넣다" },
      { id: 4, day: 17, word: "remain", meaning: "~한 상태를 유지하다" },
      { id: 5, day: 17, word: "make a distinction", meaning: "구별하다" },
      { id: 6, day: 17, word: "on average", meaning: "평균적으로" },
      { id: 7, day: 17, word: "resident", meaning: "거주자, 주민" },
      { id: 8, day: 17, word: "indispensable", meaning: "없어서는 안될" },
      { id: 9, day: 17, word: "gut feeling", meaning: "직감" },
    ],
  },
  {
    id: 17,
    list: [
      { id: 0, day: 18, word: "display", meaning: "전시하다" },
      { id: 1, day: 18, word: "distinguish", meaning: "구별하다, 구분하다" },
      { id: 2, day: 18, word: "donate", meaning: "기부하다, 기증하다" },
      { id: 3, day: 18, word: "emerge", meaning: "나오다, 생겨나다" },
      { id: 4, day: 18, word: "enable", meaning: "~을 할 수 있게 하다" },
      { id: 5, day: 18, word: "encounter", meaning: "직면하다" },
      { id: 6, day: 18, word: "encourage", meaning: "격려하다, 권장하다" },
      { id: 7, day: 18, word: "enhance", meaning: "향상시키다" },
      { id: 8, day: 18, word: "ensure", meaning: "보장하다" },
      { id: 9, day: 18, word: "essential", meaning: "꼭 필요한" },
    ],
  },
  {
    id: 18,
    list: [
      { id: 0, day: 19, word: "establish", meaning: "설립하다" },
      { id: 1, day: 19, word: "evaluate", meaning: "평가하다" },
      { id: 2, day: 19, word: "testimony", meaning: "증언, 증거" },
      { id: 3, day: 19, word: "expert", meaning: "전문가" },
      { id: 4, day: 19, word: "deprive A of B", meaning: "A에게서 B를 빼앗다" },
      { id: 5, day: 19, word: "facility", meaning: "시설, 설비" },
      { id: 6, day: 19, word: "factor", meaning: "요인, 요소, 원인" },
      { id: 7, day: 19, word: "autonomous", meaning: "자발적인" },
      { id: 8, day: 19, word: "figure", meaning: "수치" },
      { id: 9, day: 19, word: "function", meaning: "기능" },
    ],
  },
  {
    id: 19,
    list: [
      { id: 0, day: 20, word: "fundamental", meaning: "기본적인" },
      { id: 1, day: 20, word: "gender", meaning: "성별" },
      { id: 2, day: 20, word: "gene", meaning: "유전자" },
      { id: 3, day: 20, word: "generate", meaning: "만들어 내다" },
      { id: 4, day: 20, word: "indicate", meaning: "보여주다, 나타내다" },
      { id: 5, day: 20, word: "adjust", meaning: "적응/조절하다" },
      { id: 6, day: 20, word: "identify", meaning: "알아보다, 밝히다" },
      { id: 7, day: 20, word: "impact", meaning: "영향(력)" },
      { id: 8, day: 20, word: "serve as", meaning: "~한 역할을 하다" },
      { id: 9, day: 20, word: "restriction", meaning: "제한, 제약" },
    ],
  },
];
